title: Extraordinary Engineer
description: Stories from startups & engineering
baseurl: "/ordinaryengineer"
collections:
  essays:
    output: true
    permalink: /essays/:name/
  about:
    output: true
    permalink: /about/:name/
